"""System voices from Alibaba's voice list (checked 2026-10-01).

https://help.aliyun.com/zh/model-studio/qwen-audio-tts-voice-list
Cloned and additional base voices remain available through Custom voice ID.
"""

VOICES: dict[str, list[tuple[str, str]]] = {
    "qwen-audio-3.1-tts-flash": [
        ("龙安欢", "longanhuan_v3.1"),
        ("龙安灵心", "longanlingxin_v3.1"),
        ("龙安风悦", "longanfengyue_v3.1"),
        ("许南川", "xunanchuan_v3.1"),
        ("于小云", "yuxiaoyun_v3.1"),
        ("乔小娇", "qiaoxiaojiao_v3.1"),
        ("夏小晨", "xiaxiaochen_v3.1"),
        ("安明远", "anmingyuan_v3.1"),
        ("温怀清", "wenhuaiqing_v3.1"),
        ("安小岚", "anxiaolan_v3.1"),
        ("谢舒柔", "xieshurou_v3.1"),
        ("白清岚", "baiqinglan_v3.1"),
        ("许玉远", "xuyuyuan_v3.1"),
        ("安若柔", "anruorou_v3.1"),
        ("闻怀之", "wenhuaizhi_v3.1"),
        ("萧行之", "xiaoxingzhi_v3.1"),
        ("顾云舒", "guyunshu_v3.1"),
        ("霍拙石", "huozhuoshi_v3.1"),
        ("叶清禾", "yeqinghe_v3.1"),
        ("云欢欢", "yunhuanhuan_v3.1"),
        ("徐小俏", "xuxiaoqiao_v3.1"),
        ("白安然", "baianran_v3.1"),
        ("许言初", "xuyanchu_v3.1"),
        ("叶知晴", "yezhiqing_v3.1"),
        ("安迪", "andi_v3.1"),
        ("安语晴", "anyuqing_v3.1"),
        *[
            (f"{name} · English", f"{name}_v3.1")
            for name in (
                "Emily",
                "Luna",
                "Eric",
                "Luca",
                "Abby",
                "Annie",
                "Ava",
                "Beth",
                "Betty",
                "Cally",
                "Cindy",
                "Donna",
                "Andy",
                "Brian",
                "David",
            )
        ],
        ("龙安元妃", "longanyuanfei_v3.1"),
        ("龙杰力豆", "longjielidou_v3.1"),
        ("龙安灵希", "longanlingxi_v3.1"),
        ("龙火火", "longhuohuo_v3.1"),
        ("龙应桃", "longyingtao_v3.1"),
        ("龙安雅", "longanya_v3.1"),
        ("龙婉", "longwan_v3.1"),
        ("龙星", "longxing_v3.1"),
        ("龙华", "longhua_v3.1"),
        ("龙寒", "longhan_v3.1"),
        ("龙安智", "longanzhi_v3.1"),
        ("龙哲", "longzhe_v3.1"),
        ("龙安洋", "longanyang_v3.1"),
        ("李白", "libai_v3.1"),
        ("龙铃", "longling_v3.1"),
        ("龙牛牛", "longniuniu_v3.1"),
        ("龙闪闪", "longshanshan_v3.1"),
        ("龙泡泡", "longpaopao_v3.1"),
        ("loongstella", "loongstella_v3.1"),
        ("龙媛", "longyuan_v3.1"),
        ("龙妙", "longmiao_v3.1"),
        ("龙三叔", "longsanshu_v3.1"),
        ("龙安莉", "longanli_v3.1"),
        ("龙安温", "longanwen_v3.1"),
        ("龙安朗", "longanlang_v3.1"),
        ("龙小夏", "longxiaoxia_v3.1"),
        ("龙安冲", "longanchong_v3.1"),
    ],
    "qwen-audio-3.0-tts-plus": [
        ("龙安灵心", "longanlingxin"),
        ("龙安鲁风", "longanlufeng"),
    ],
    "qwen-audio-3.0-tts-flash": [
        ("龙安风悦", "longanfengyue"),
        ("龙安元妃", "longanyuanfei"),
        ("龙安灵希", "longanlingxi"),
        ("龙安小昕", "longanxiaoxin"),
        ("龙安欢", "longanhuan_v3.6"),
        ("龙杰力豆", "longjielidou_v3.6"),
        ("龙泡泡", "longpaopao_v3.6"),
        ("龙火火", "longhuohuo_v3.6"),
        ("龙川叔", "longchuanshu_v3.6"),
        ("loongmary · English", "loongmary"),
        ("loongeva · English", "loongeva_v3.6"),
        ("loongJohn · English", "loongjohn"),
    ],
}
